name: Build
on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          name: "Ubuntu GCC", artifact: "qi-linux.tar.gz",
          os: ubuntu-22.04,
          cc: "gcc-12", cxx: "g++-12"
        }
        - {
          name: "macOS", artifact: "qi-macos.tar.gz",
          os: macos-14,
          cc: "clang", cxx: "clang++"
        }

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - uses: ashutoshvarma/setup-ninja@master

      - name: Restore vcpkg binary cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/vcpkg/
          key: ${{runner.os}}-${{hashFiles( 'vcpkg.json' ) }}-${{hashFiles( '.git/modules/cmake/HEAD' )}}-vcpkg-cache

      - name: Build
        shell: bash
        env:
          CC: ${{matrix.config.cc}}
          CXX: ${{matrix.config.cxx}}
        run: |
          ./bootstrap.sh
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install python package
        run: |
          python -m pip install --upgrade pip
          pip install nipype
          pip install -e ./Python/

      - name: Tests
        working-directory: ./Python/Tests
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: |
          export PATH="$PWD/../../build/Source:$PATH"; python -m unittest discover

      - name: Tarball
        run: |
          cd ${{github.workspace}}
          mv ./build/Source/qi ./
          ALL="qi"
          if [ "${{runner.os}}" == "macOS" ]; then
            echo "Using GNU tar"
            gtar -cvzf ${{matrix.config.artifact}} $ALL
          else
            echo "Using system tar"
            tar -cvzf ${{matrix.config.artifact}} $ALL
          fi
        shell: bash

      - name: Release
        if: contains(github.ref, 'tags/v')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{github.workspace}}/${{matrix.config.artifact}}
          artifactErrorsFailBuild: true
          draft: true
